workflows:
  react-native:
    name: React Native App new
    environment:
      vars:
        XCODE_WORKSPACE: 'Apprene'
        XCODE_SCHEME: 'Apprene'

      node: latest
      xcode: latest
      cocoapods: default

    scripts:
      - cd android && chmod +x gradlew
      - npm install
      - echo "sdk.dir=$HOME/programs/android-sdk-macosx" > "$FCI_BUILD_DIR/android/local.properties"
      - echo $(jq .'build' build_data/data.json)
      - |
        if [[ $(jq -r .'build' build_data/data.json) == "android" ]] || [[ $(jq -r ."build" build_data/data.json) == "both" ]] ; then
        echo "block executed";
        # build Android;
        cd android;
        ./gradlew assembleRelease;
        fi
      - |
        if [[ $(jq -r ."build" build_data/data.json) == "ios" ]] || [[ $(jq -r ."build" build_data/data.json) == "both" ]] ; then
        # build iOS
        cd ios
        pod install
        ls
         # build iOS
                cd ios
                pod install
                react-native bundle --entry-file='index.js' --bundle-output='./ios/app/main.jsbundle' --dev=false --platform='ios' --assets-dest='./ios'
                ls
                # xcodebuild build -workspace "$XCODE_WORKSPACE.xcworkspace" -scheme "$XCODE_SCHEME" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
                xcodebuild -sdk iphonesimulator -workspace "$XCODE_WORKSPACE.xcworkspace" -scheme "$XCODE_SCHEME" -configuration Debug
                fi 
    artifacts:
      - android/app/build/outputs/**/*.apk
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
